web/archive/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("<int:pk>/", views.ArchiveDetailView.as_view(), name="archive_detail"),
]

web/core/urls.py
from django.urls import path
from django.views import generic

from . import views

app_name = "core"
urlpatterns = [
    path("", generic.TemplateView.as_view(template_name="home.html"), name="home"),
]

urlpatterns += [
    path("dashboard/archives/", views.ArchiveListView.as_view(), name="archives"),
    path(
        "dashboard/archives/<str:username>/",
        views.UserArchiveListView.as_view(),
        name="user_archives",
    ),
    path(
        "dashboard/archive/new/",
        views.ArchiveCreateView.as_view(),
        name="archive_create",
    ),
    path(
        "dashboard/archive/<int:pk>/update/",
        views.ArchiveUpdateView.as_view(),
        name="archive_update",
    ),
    path(
        "dashboard/archive/<int:pk>/delete/",
        views.ArchiveDeleteView.as_view(),
        name="archive_delete",
    ),
]

web/webarsipums/urls.py
# from django.conf import settings
# from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

admin.site.site_header = "Web Arsip dan Dokumen UMS"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("account/", include("account.urls")),
    path("archive/", include("archive.urls")),
    path("search/", include("search.urls")),
]

# Expose media files
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/core/models.py
import os

from django.contrib.auth.models import User
from django.contrib.postgres.search import (
    SearchQuery,
    SearchRank,
    SearchVector,
    TrigramSimilarity,
)
from django.db import models
from django.urls import reverse

# from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="default-avatar.png", upload_to="profiles")

    def __str__(self):
        return f"{self.user.username} Profile"

    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)

    #     img = Image.open(self.image.path)

    #     if img.height > 300 or img.width > 300:
    #         output_size = (300, 300)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)


def media_path(instance, filename):
    """Mengembalikan nama direktori + file untuk unggah sebuah berkas baru"""
    from uuid import uuid4

    ext = filename.split(".")[-1]
    filename = f"{uuid4().hex}.{ext}"

    return os.path.join("archives", filename)


# Search Engine using PostgreSQL search
class ArchiveManager(models.Manager):
    def search(self, text):
        language = "indonesian"
        search_vectors = SearchVector(
            "nama", weight="A", config=language
        ) + SearchVector("deskripsi", weight="B", config=language)
        search_query = SearchQuery(text, config=language)
        search_rank = SearchRank(search_vectors, search_query)
        trigram_similarity = TrigramSimilarity("nama", text)
        return (
            self.get_queryset()
            .annotate(search=search_vectors)
            .filter(search=search_query)
            .annotate(rank=search_rank + trigram_similarity)
            .order_by("-rank")
        )


class Archive(models.Model):
    """
    Model untuk menyimpan berkas arsip
    > nama file harus diubah menjadi 32 karakter acak dan unik,
    > jika nama sudah ada dicari nama lain nama direktori tersembunyi dari user,
    > nama file baru dikembalikan ke user
    """

    pengunggah = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True
    )
    nama = models.CharField(
        max_length=200, help_text="Ketik nama arsip (contoh: SK Rektor No. III)",
    )
    deskripsi = models.TextField(
        blank=True, null=True, help_text="Deskripsi atau ringkasan pendek isi arsip"
    )
    tanggal_unggah = models.DateField(auto_now_add=True)

    JENIS_ARSIP = (
        (0, "Surat Keputusan"),
        (1, "Surat Tugas"),
        (2, "Sertifikat"),
        (3, "Ijazah"),
        (4, "Dokumen"),
        (5, "Foto"),
    )
    jenis = models.IntegerField(
        db_column="cJenis",
        blank=True,
        null=True,
        default=0,
        choices=JENIS_ARSIP,
        help_text="Pilih jenis arsip",
    )

    SIFAT_CHOICES = (
        # dapat diakses seluruh dunia, jika tahu link-nya
        (0, "Publik"),
        # dapat diakses seluruh dunia, sementara dalam rentang tanggal tertentu
        (1, "Publik (temp)"),
        # dapat diakses hanya oleh aplikasi di UMS
        (2, "Internal"),
        # dapat diakses oleh yang mengunggah (atas nama orang/lembaga)
        (3, "Pribadi"),
    )
    sifat = models.IntegerField(
        db_column="cSifat",
        blank=True,
        null=True,
        default=0,
        choices=SIFAT_CHOICES,
        help_text="Pilih sifat arsip",
    )

    publik_mulai = models.DateField(
        blank=True, null=True, help_text="Tanggal arsip mulai bisa diakses publik"
    )
    publik_berakhir = models.DateField(
        blank=True, null=True, help_text="Tanggal arsip terakhir bisa diakses publik"
    )
    file_media = models.FileField(
        "File",
        default="default-file.pdf",
        upload_to=media_path,
        help_text="File fisik arsip",
    )

    objects = ArchiveManager()

    class Meta:
        ordering = ["tanggal_unggah"]

    def extension(self):
        name, extension = os.path.splitext(self.file_media.name)
        return extension[1:].upper()

    def __str__(self):
        """String untuk merepresentasikan object Model."""
        return self.nama

    def get_absolute_url(self):
        return reverse("archive_detail", kwargs={"pk": self.pk})

web/archive/views.py
from django.views import generic

from core.models import Archive


class ArchiveDetailView(generic.DetailView):
    model = Archive
    template_name = "archive/archive_detail.html"

web/archive/templates/archive/archive_detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<!-- Navbar -->
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="collapse-brand d-md-block mr-3" style="display: none;">
        <a href="{% url 'core:home' %}">
          <img src="{% static 'img/brand/logo.png' %}" style="height: 50px;">
        </a>
      </div>
      <!-- Search form -->
      <form method="GET" action="{% url 'search' %}" id="navbar-search-main"
        class="navbar-search navbar-search-light form-inline mr-sm-3">
        <div class="form-group mb-0">
          <div class="input-group input-group-alternative input-group-merge">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-search"></i></span>
            </div>
            <input class="form-control" id="q" name="q" type="text" placeholder="Cari arsip...">
          </div>
        </div>
        <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main"
          aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </form>
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center  ml-md-auto ">
        <li class="nav-item d-sm-none">
          <a class="nav-link" href="{% url 'core:home' %}">
            <i class="ni ni-shop"></i>
          </a>
        </li>
        <li class="nav-item d-sm-none">
          <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
            <i class="ni ni-zoom-split-in"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
                <img alt="Image placeholder" src="{{ user.profile.image.url }}">
              </span>
              <div class="media-body  ml-2  d-none d-lg-block">
                <span class="mb-0 text-sm  font-weight-bold">{{ user.get_username }}</span>
              </div>
            </div>
          </a>
          <div class="dropdown-menu  dropdown-menu-right ">
            <div class="dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome!</h6>
            </div>
            <a href="{% url 'profile' %}" class="dropdown-item">
              <i class="ni ni-single-02"></i>
              <span>My profile</span>
            </a>
            <a href="{% url 'core:archives' %}" class="dropdown-item">
              <i class="ni ni-books"></i>
              <span>Library</span>
            </a>
            <div class="dropdown-divider"></div>
            <a href="#!" class="dropdown-item" data-toggle="modal" data-target="#modal-logout">
              <i class="ni ni-user-run"></i>
              <span>Logout</span>
            </a>
          </div>
        </li>
        {% else %}
        <li class="nav-item d-lg-block ml-lg-4">
          <a href="{% url 'login' %}" class="btn btn-neutral btn-icon">
            <span class="btn-inner--icon">
              <i class="ni ni-single-02"></i>
            </span>
            <span class="nav-link-inner--text d-md-inline ml-2" style="display: none;">Login</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<div id="page-container">
  <div id="content-wrap" class="main-content">
    {% block messages %}{% endblock %}
    <section class="py-4">
      <div class="container-fluid my-5 my-lg-5">
        <div class="row justify-content-center">
          <div class="col-lg-11 col-md-11">
            <div class="card bg-secondary shadow border-0">
              <div class="card-header bg-white border-0">
                <div class="row align-items-center">
                  <div class="col-8">
                    <h1 class="card-title mb-0">{{ archive.nama }}</h1>
                  </div>
                </div>
              </div>
              <div class="card-body">
                <p>
                  <strong>oleh</strong> <a href="#">{{ archive.pengunggah.get_full_name }}</a>
                </p>
                <div class="row">
                  <div class="col-3">
                    <div><strong>Tanggal publikasi</strong></div>
                    <div><strong>Jenis</strong></div>
                    <div><strong>Summary</strong></div>
                  </div>
                  <div class="col-9">
                    <div>{{ archive.tanggal_unggah|date:'d F Y' }}</div>
                    <div>{{ archive.get_jenis_display }}</div>
                    <div>{{ archive.deskripsi }}</div>
                  </div>
                </div>
                <div class="mx-2 my-4">
                  <h4>{{ archive.get_sifat_display }}</h4>
                  {% if archive.publik_mulai or archive.publik_berakhir %}
                  <p><strong class="text-success">Available:</strong>
                    {{ archive.publik_mulai|date:'d F Y' }} - {{ archive.publik_berakhir|date:'d F Y' }}
                  </p>
                  {% endif %}
                </div>

                {% if archive.file_media %}
                <a href="{{ archive.file_media.url }}" target="_blank" class="btn btn-icon btn-primary">
                  <span class="btn-inner--icon"><i class="ni ni-cloud-download-95"></i></span>
                  <span class="btn-inner--text">Download</span>
                </a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- Modal -->
    {% include 'partials/_modal.html' %}
  </div>

  <!-- Footer -->
  <div id="footer">
    <!-- Footer -->
    <footer class="py-5 border-top" id="footer-main">
      <div class="container">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="copyright text-center text-xl-left text-muted">
              &copy;
              <script>
                document.write(new Date().getFullYear())
              </script> <a href="https://www.ums.ac.id" class="font-weight-bold ml-1" target="_blank">
                Universitas Muhammadiyah Surakarta
              </a>
            </div>
          </div>
          <div class="col-xl-6">
            <ul class="nav nav-footer justify-content-center justify-content-xl-end">
              <li class="nav-item">
                <a href="http://bti.ums.ac.id" class="nav-link" target="_blank">Biro TI</a>
              </li>
              <li class="nav-item">
                <a href="https://github.com/creativetimofficial/argon-design-system/blob/master/LICENSE.md"
                  class="nav-link" target="_blank">MIT License</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </div>
</div>
{% endblock %}