web/archive/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("<int:pk>/", views.ArchiveDetailView.as_view(), name="archive_detail"),
]

web/core/urls.py
from django.urls import path
from django.views import generic

from . import views

app_name = "core"
urlpatterns = [
    path("", generic.TemplateView.as_view(template_name="home.html"), name="home"),
]

urlpatterns += [
    path("dashboard/archives/", views.ArchiveListView.as_view(), name="archives"),
    path(
        "dashboard/archives/<str:username>/",
        views.UserArchiveListView.as_view(),
        name="user_archives",
    ),
    path(
        "dashboard/archive/new/",
        views.ArchiveCreateView.as_view(),
        name="archive_create",
    ),
    path(
        "dashboard/archive/<int:pk>/update/",
        views.ArchiveUpdateView.as_view(),
        name="archive_update",
    ),
    path(
        "dashboard/archive/<int:pk>/delete/",
        views.ArchiveDeleteView.as_view(),
        name="archive_delete",
    ),
]

web/webarsipums/urls.py
# from django.conf import settings
# from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

admin.site.site_header = "Web Arsip dan Dokumen UMS"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("account/", include("account.urls")),
    path("archive/", include("archive.urls")),
    path("search/", include("search.urls")),
]

# Expose media files
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/core/models.py
import os

from django.contrib.auth.models import User
from django.contrib.postgres.search import (
    SearchQuery,
    SearchRank,
    SearchVector,
    TrigramSimilarity,
)
from django.db import models
from django.urls import reverse

# from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="default-avatar.png", upload_to="profiles")

    def __str__(self):
        return f"{self.user.username} Profile"

    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)

    #     img = Image.open(self.image.path)

    #     if img.height > 300 or img.width > 300:
    #         output_size = (300, 300)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)


def media_path(instance, filename):
    """Mengembalikan nama direktori + file untuk unggah sebuah berkas baru"""
    from uuid import uuid4

    ext = filename.split(".")[-1]
    filename = f"{uuid4().hex}.{ext}"

    return os.path.join("archives", filename)


# Search Engine using PostgreSQL search
class ArchiveManager(models.Manager):
    def search(self, text):
        language = "indonesian"
        search_vectors = SearchVector(
            "nama", weight="A", config=language
        ) + SearchVector("deskripsi", weight="B", config=language)
        search_query = SearchQuery(text, config=language)
        search_rank = SearchRank(search_vectors, search_query)
        trigram_similarity = TrigramSimilarity("nama", text)
        return (
            self.get_queryset()
            .annotate(search=search_vectors)
            .filter(search=search_query)
            .annotate(rank=search_rank + trigram_similarity)
            .order_by("-rank")
        )


class Archive(models.Model):
    """
    Model untuk menyimpan berkas arsip
    > nama file harus diubah menjadi 32 karakter acak dan unik,
    > jika nama sudah ada dicari nama lain nama direktori tersembunyi dari user,
    > nama file baru dikembalikan ke user
    """

    pengunggah = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True
    )
    nama = models.CharField(
        max_length=200, help_text="Ketik nama arsip (contoh: SK Rektor No. III)",
    )
    deskripsi = models.TextField(
        blank=True, null=True, help_text="Deskripsi atau ringkasan pendek isi arsip"
    )
    tanggal_unggah = models.DateField(auto_now_add=True)

    JENIS_ARSIP = (
        (0, "Surat Keputusan"),
        (1, "Surat Tugas"),
        (2, "Sertifikat"),
        (3, "Ijazah"),
        (4, "Dokumen"),
        (5, "Foto"),
    )
    jenis = models.IntegerField(
        db_column="cJenis",
        blank=True,
        null=True,
        default=0,
        choices=JENIS_ARSIP,
        help_text="Pilih jenis arsip",
    )

    SIFAT_CHOICES = (
        # dapat diakses seluruh dunia, jika tahu link-nya
        (0, "Publik"),
        # dapat diakses seluruh dunia, sementara dalam rentang tanggal tertentu
        (1, "Publik (temp)"),
        # dapat diakses hanya oleh aplikasi di UMS
        (2, "Internal"),
        # dapat diakses oleh yang mengunggah (atas nama orang/lembaga)
        (3, "Pribadi"),
    )
    sifat = models.IntegerField(
        db_column="cSifat",
        blank=True,
        null=True,
        default=0,
        choices=SIFAT_CHOICES,
        help_text="Pilih sifat arsip",
    )

    publik_mulai = models.DateField(
        blank=True, null=True, help_text="Tanggal arsip mulai bisa diakses publik"
    )
    publik_berakhir = models.DateField(
        blank=True, null=True, help_text="Tanggal arsip terakhir bisa diakses publik"
    )
    file_media = models.FileField(
        "File",
        default="default-file.pdf",
        upload_to=media_path,
        help_text="File fisik arsip",
    )

    objects = ArchiveManager()

    class Meta:
        ordering = ["tanggal_unggah"]

    def extension(self):
        name, extension = os.path.splitext(self.file_media.name)
        return extension[1:].upper()

    def __str__(self):
        """String untuk merepresentasikan object Model."""
        return self.nama

    def get_absolute_url(self):
        return reverse("archive_detail", kwargs={"pk": self.pk})

web/core/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name"]


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["image"]

web/archive/views.py
from django.views import generic

from core.models import Archive


class ArchiveDetailView(generic.DetailView):
    model = Archive
    template_name = "archive/archive_detail.html"

web/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views import generic

from core.models import Archive

# Archive board


class ArchiveListView(LoginRequiredMixin, generic.ListView):
    model = Archive
    template_name = "dashboard/archive_list.html"
    ordering = ["-tanggal_unggah"]

    def get_queryset(self):
        return self.model.objects.all().exclude(sifat=3)


class UserArchiveListView(LoginRequiredMixin, generic.ListView):
    model = Archive
    template_name = "dashboard/user_archives.html"
    ordering = ["-tanggal_unggah"]

    def get_queryset(self):
        return self.model.objects.filter(pengunggah=self.request.user)


class ArchiveCreateView(LoginRequiredMixin, generic.CreateView):
    model = Archive
    template_name = "dashboard/archive_form.html"
    fields = [
        "nama",
        "deskripsi",
        "jenis",
        "sifat",
        "publik_mulai",
        "publik_berakhir",
        "file_media",
    ]
    success_url = reverse_lazy("core:archives")

    def form_valid(self, form):
        form.instance.pengunggah = self.request.user
        return super().form_valid(form)


class ArchiveUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Archive
    template_name = "dashboard/archive_form.html"
    fields = [
        "nama",
        "deskripsi",
        "jenis",
        "sifat",
        "publik_mulai",
        "publik_berakhir",
        "file_media",
    ]
    success_url = reverse_lazy("core:archives")

    def test_func(self):
        archive = self.get_object()
        if self.request.user == archive.pengunggah:
            return True
        return False


class ArchiveDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Archive
    success_url = reverse_lazy("core:archives")

    def test_func(self):
        archive = self.get_object()
        if self.request.user == archive.pengunggah:
            return True
        return False

web/core/templates/dashboard/archive_form.html
{% extends 'dashboard/base.html' %}

{% load static %}

{% block content_header %}
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item">
                <a href="{% url 'core:home' %}"><i class="fas fa-home"></i></a>
              </li>
              <li class="breadcrumb-item"><a href="{% url 'core:archives' %}">Archives</a></li>
              <li class="breadcrumb-item active" aria-current="page">New</li>
            </ol>
          </nav>
        </div>
        <div class="col-lg-6 col-5 text-right">
          <a href="{% url 'core:archives' %}" class="btn btn-sm btn-neutral">Back to list</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block page_content %}
<!-- Archive form -->
<div class="card">
  <!-- Card header -->
  <div class="card-header">
    <h3 class="mb-0">Add archive</h3>
  </div>
  <!-- Card body -->
  <div class="card-body">
    <form action="" method="POST" enctype="multipart/form-data" autocomplete="off">
      {% csrf_token %}
      <div class="form-group row">
        <label for="{{ form.nama.id_for_label }}"
          class="col-md-2 col-form-label form-control-label">{{ form.nama.label }}</label>
        <div class="col-md-7">
          <input id="{{ form.nama.id_for_label }}" class="form-control" name="{{ form.nama.html_name }}" type="text"
            placeholder="{{ form.nama.label }}" value="{{ form.nama.value|default:'' }}" required>
        </div>
      </div>
      <div class="form-group row">
        <label for="{{ form.deskripsi.id_for_label }}"
          class="col-md-2 col-form-label form-control-label">{{ form.deskripsi.label }}</label>
        <div class="col-md-7">
          <textarea rows="5" id="{{ form.deskripsi.id_for_label }}" class="form-control"
            name="{{ form.deskripsi.html_name }}" placeholder="{{ form.deskripsi.label }}"
            required>{{ form.deskripsi.value|default:'' }}</textarea>
        </div>
      </div>
      <div class="form-group row">
        <label for="{{ form.jenis.id_for_label }}"
          class="col-md-2 col-form-label form-control-label">{{ form.jenis.label }}</label>
        <div class="col-md-7">
          <select id="{{ form.jenis.id_for_label }}" class="form-control" name="{{ form.jenis.html_name }}">
            {% for x,y in form.fields.jenis.choices %}
            <option value="{{ x }}" {% if form.jenis.value == x %}selected{% endif %}>{{ y }}</option>
            {% endfor %}
          </select>
        </div>
      </div>
      <div class="form-group row">
        <label for="{{ form.sifat.id_for_label }}"
          class="col-md-2 col-form-label form-control-label">{{ form.sifat.label }}</label>
        <div class="col-md-7">
          <select id="{{ form.sifat.id_for_label }}" class="form-control" name="{{ form.sifat.html_name }}">
            {% for x,y in form.fields.sifat.choices %}
            <option value="{{ x }}" {% if form.sifat.value == x %}selected{% endif %}>{{ y }}</option>
            {% endfor %}
          </select>
        </div>
      </div>
      <div id="temp-dateset" class="row mb-4" {% if form.sifat.value != 1 %}style="display: none;"{% endif %}>
        <div class="col-md-2"></div>
        <div class="col-md-7">
          <div class="row input-daterange datepicker align-items-center">
            <div class="col">
              <div class="form-group">
                <label for="{{ form.publik_mulai.id_for_label }}"
                  class="form-control-label">{{ form.publik_mulai.label }}</label>
                <input id="{{ form.publik_mulai.id_for_label }}" class="form-control"
                  name="{{ form.publik_mulai.html_name }}" placeholder="Start date" type="text"
                  value="{{ form.publik_mulai.value|date:'m/d/Y' }}">
              </div>
            </div>
            <div class="col">
              <div class="form-group">
                <label for="{{ form.publik_berakhir.id_for_label }}"
                  class="form-control-label">{{ form.publik_berakhir.label }}</label>
                <input id="{{ form.publik_berakhir.id_for_label }}" class="form-control"
                  name="{{ form.publik_berakhir.html_name }}" placeholder="End date" type="text"
                  value="{{ form.publik_berakhir.value|date:'m/d/Y' }}">
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-md-2 col-form-label form-control-label">{{ form.file_media.label }}</label>
        <div class="col-md-7">
          <div class="custom-file">
            <input id="{{ form.file_media.id_for_label }}" class="custom-file-input"
              name="{{ form.file_media.html_name }}" type="file" lang="en">
            <label for="{{ form.file_media.id_for_label }}" class="custom-file-label"></label>
          </div>
          {% if form.file_media.value %}
          <div class="text-sm mt-2 ml-2">
            Current file:
            <a href="{{ form.instance.file_media.url }}">{{ form.file_media.value }}</a>
          </div>
          {% endif %}
        </div>
      </div>
      <div class="text-center mt-7">
        <button type="submit" class="btn btn-primary">Save</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

{% block content_scripts %}
<script>
  $(document).ready(function () {
    $('#id_sifat').change(function () {
      var value = $(this).val()
      if (value === '1') {
        $('#temp-dateset').show();
      }
      else {
        $('#id_publik_mulai').val('');
        $('#id_publik_berakhir').val('');
        $('#temp-dateset').hide();
      }
    });
  });
</script>
{% endblock %}

web/core/templates/dashboard/archive_list.html
{% extends 'dashboard/base.html' %}

{% load static %}

{% block content_header %}
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item">
                <a href="{% url 'core:home' %}"><i class="fas fa-home"></i></a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">Archives</li>
            </ol>
          </nav>
        </div>
        <div class="col-lg-6 col-5 text-right">
          <a href="{% url 'core:archive_create' %}" class="btn btn-sm btn-neutral">New</a>
          <a href="{% url 'core:user_archives' user.get_username %}" class="btn btn-sm btn-neutral">Filter</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block page_content %}
<!-- Table -->
<div class="row">
  <div class="col">
    <div class="card">
      <!-- Card header -->
      <div class="card-header">
        <h3 class="mb-0">Archives</h3>
        <p class="text-sm mb-0">
          Disini daftar semua arsip yang ada di database UMS
        </p>
      </div>
      <div class="table-responsive py-4">
        <table class="table table-flush" id="datatable-archive">
          <thead class="thead-light">
            <tr>
              <th>Pengunggah</th>
              <th>Nama</th>
              <th>Jenis</th>
              <th>Sifat</th>
              <th>Tanggal unggah</th>
              <th>Action</th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th>Pengunggah</th>
              <th>Nama</th>
              <th>Jenis</th>
              <th>Sifat</th>
              <th>Tanggal unggah</th>
              <th>Action</th>
            </tr>
          </tfoot>
          <tbody>
            {% for archive in archive_list %}
            <tr>
              <td>{{ archive.pengunggah }}</td>
              <td><a href="{% url 'archive_detail' archive.pk %}" class="font-weight-bold">{{ archive.nama }}</a></td>
              <td>{{ archive.get_jenis_display }}</td>
              <td>{{ archive.get_sifat_display }}</td>
              <td>{{ archive.tanggal_unggah }}</td>
              <td class="table-actions">
                {% if archive.pengunggah == user %}
                <a href="{% url 'core:archive_update' archive.pk %}" class="table-action mr-3" data-toggle="tooltip"
                  data-original-title="Edit product">
                  <i class="fas fa-edit"></i>
                </a>
                <a href="#!" class="table-action table-action-delete mr-3" data-toggle="modal"
                  data-target="#modal-archive{{ archive.pk }}" data-original-title="Delete product">
                  <i class="fas fa-trash"></i>
                </a>
                <div class="modal fade" id="modal-archive{{ archive.pk }}" tabindex="-1" role="dialog"
                  aria-labelledby="modal-archive{{ archive.pk }}" aria-hidden="true">
                  <form action="{% url 'core:archive_delete' archive.pk %}" method="POST">
                    {% csrf_token %}
                    <div class="modal-dialog modal-danger modal-dialog-centered modal-sm" role="document">
                      <div class="modal-content bg-gradient-danger">
                        <div class="modal-header">
                          <h6 class="modal-title">{{ archive.nama }}</h6>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <div class="text-center">
                            <i class="ni ni-archive-2 ni-3x"></i>
                            <p class="mt-4">Are you sure you want to delete this archive?</p>
                          </div>
                        </div>
                        <div class="modal-footer">
                          <button type="submit" class="btn btn-white">Yes</button>
                          <button type="button" class="btn btn-link text-white ml-auto" data-dismiss="modal">No</button>
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
                {% endif %}
              </td>
            </tr>
            {% empty %}
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

web/core/templates/dashboard/base.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<!-- Sidebar -->
<nav class="sidenav navbar navbar-vertical fixed-left navbar-expand-xs navbar-light bg-white" id="sidenav-main">
  <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="sidenav-header d-flex align-items-center">
      <a class="navbar-brand" href="{% url 'core:home' %}">
        <img src="{% static 'img/brand/logo.png' %}" class="navbar-brand-img" style="max-height: 2.5rem;" alt="...">
      </a>
      <div class="ml-auto mr-4">
        <!-- Sidenav toggler -->
        <div class="sidenav-toggler d-md-none" data-action="sidenav-unpin" data-target="#sidenav-main">
          <div class="sidenav-toggler-inner">
            <i class="sidenav-toggler-line"></i>
            <i class="sidenav-toggler-line"></i>
            <i class="sidenav-toggler-line"></i>
          </div>
        </div>
      </div>
    </div>
    <div class="navbar-inner">
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Nav items -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:archives' %}">
              <i class="ni ni-archive-2 text-orange"></i>
              <span class="nav-link-text">Archives</span>
            </a>
          </li>
        </ul>
        <!-- Divider -->
        <hr class="my-3">
        <!-- Heading -->
        <h6 class="navbar-heading p-0 text-muted">
          <span class="docs-normal">User</span>
        </h6>
        <!-- Navigation -->
        <ul class="navbar-nav mb-md-3">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' %}">
              <i class="ni ni-single-02"></i>
              <span class="nav-link-text">Profile</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#!" data-toggle="modal" data-target="#modal-logout">
              <i class="ni ni-user-run"></i>
              <span class="nav-link-text">Logout</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

<div class="main-content" id="panel">
  <!-- Navbar -->
  <nav
    class="navbar navbar-top navbar-expand navbar-dark {% if request.resolver_match.url_name == 'profile' %}bg-default{% else %}bg-primary{% endif %} border-bottom">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Navbar links -->
        <ul class="navbar-nav align-items-center  ml-md-auto ">
          <li class="nav-item d-xl-none">
            <!-- Sidenav toggler -->
            <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin"
              data-target="#sidenav-main">
              <div class="sidenav-toggler-inner">
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
              </div>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
          <li class="nav-item dropdown">
            <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              <div class="media align-items-center">
                <span class="avatar avatar-sm rounded-circle">
                  <img alt="Image placeholder" src="{{ user.profile.image.url }}">
                </span>
                <div class="media-body  ml-2  d-none d-lg-block">
                  <span class="mb-0 text-sm  font-weight-bold">{{ user.get_username }}</span>
                </div>
              </div>
            </a>
            <div class="dropdown-menu  dropdown-menu-right ">
              <div class="dropdown-header noti-title">
                <h6 class="text-overflow m-0">Welcome!</h6>
              </div>
              <a href="{% url 'profile' %}" class="dropdown-item">
                <i class="ni ni-single-02"></i>
                <span>My profile</span>
              </a>
              <div class="dropdown-divider"></div>
              <a href="#!" class="dropdown-item" data-toggle="modal" data-target="#modal-logout">
                <i class="ni ni-user-run"></i>
                <span>Logout</span>
              </a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Header -->
  {% block content_header %}
  {% endblock %}

  <div class="container-fluid mt--6">
    <!-- Page content -->
    {% block page_content %}
      {% block messages %}{% endblock %}
    {% endblock %}

    <!-- Modal -->
    {% include 'partials/_modal.html' %}

    <!-- Footer -->
    <footer class="footer pt-0">
      <div class="row align-items-center justify-content-lg-between">
        <div class="col-lg-6">
          <div class="copyright text-center  text-lg-left  text-muted">
            &copy;
            <script>
              document.write(new Date().getFullYear())
            </script> <a href="https://www.ums.ac.id" class="font-weight-bold ml-1" target="_blank">
              Universitas Muhammadiyah Surakarta
            </a>
          </div>
        </div>
        <div class="col-lg-6">
          <ul class="nav nav-footer justify-content-center justify-content-lg-end">
            <li class="nav-item">
              <a href="http://bti.ums.ac.id" class="nav-link" target="_blank">Biro TI</a>
            </li>
            <li class="nav-item">
              <a href="https://github.com/creativetimofficial/argon-design-system/blob/master/LICENSE.md"
                class="nav-link" target="_blank">MIT License</a>
            </li>
          </ul>
        </div>
      </div>
    </footer>
  </div>
</div>
{% endblock %}

{% block content_scripts %}
{% endblock %}

web/core/templates/dashboard/user_archives.html
{% extends 'dashboard/base.html' %}

{% load static %}

{% block content_header %}
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item">
                <a href="{% url 'core:home' %}"><i class="fas fa-home"></i></a>
              </li>
              <li class="breadcrumb-item"><a href="{% url 'core:archives' %}">Archives</a></li>
              <li class="breadcrumb-item active" aria-current="page">{{ user }}</li>
            </ol>
          </nav>
        </div>
        <div class="col-lg-6 col-5 text-right">
          <a href="{% url 'core:archive_create' %}" class="btn btn-sm btn-neutral">New</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block page_content %}
<!-- Table -->
<div class="row">
  <div class="col">
    <div class="card">
      <!-- Card header -->
      <div class="card-header">
        <h3 class="mb-0">Arsipku</h3>
        <p class="text-sm mb-0">
          Arsip yang telah saya upload di database UMS
        </p>
      </div>
      <div class="table-responsive py-4">
        <table class="table table-flush" id="datatable-archive">
          <thead class="thead-light">
            <tr>
              <th>Nama</th>
              <th>Jenis</th>
              <th>Sifat</th>
              <th>Tanggal unggah</th>
              <th>Action</th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th>Nama</th>
              <th>Jenis</th>
              <th>Sifat</th>
              <th>Tanggal unggah</th>
              <th>Action</th>
            </tr>
          </tfoot>
          <tbody>
            {% for archive in archive_list %}
            <tr>
              <td><a href="{% url 'archive_detail' archive.pk %}" class="font-weight-bold">{{ archive.nama }}</a></td>
              <td>{{ archive.get_jenis_display }}</td>
              <td>{{ archive.get_sifat_display }}</td>
              <td>{{ archive.tanggal_unggah }}</td>
              <td class="table-actions">
                {% if archive.pengunggah == user %}
                <a href="{% url 'core:archive_update' archive.pk %}" class="table-action mr-3" data-toggle="tooltip"
                  data-original-title="Edit product">
                  <i class="fas fa-edit"></i>
                </a>
                <a href="#!" class="table-action table-action-delete mr-3" data-toggle="modal"
                  data-target="#modal-archive{{ archive.pk }}" data-original-title="Delete product">
                  <i class="fas fa-trash"></i>
                </a>
                <div class="modal fade" id="modal-archive{{ archive.pk }}" tabindex="-1" role="dialog"
                  aria-labelledby="modal-archive{{ archive.pk }}" aria-hidden="true">
                  <form action="{% url 'core:archive_delete' archive.pk %}" method="POST">
                    {% csrf_token %}
                    <div class="modal-dialog modal-danger modal-dialog-centered modal-sm" role="document">
                      <div class="modal-content bg-gradient-danger">
                        <div class="modal-header">
                          <h6 class="modal-title">{{ archive.nama }}</h6>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <div class="text-center">
                            <i class="ni ni-archive-2 ni-3x"></i>
                            <p class="mt-4">Are you sure you want to delete this archive?</p>
                          </div>
                        </div>
                        <div class="modal-footer">
                          <button type="submit" class="btn btn-white">Yes</button>
                          <button type="button" class="btn btn-link text-white ml-auto" data-dismiss="modal">No</button>
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
                {% endif %}
              </td>
            </tr>
            {% empty %}
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}